# Generated by Django 4.0.2 on 2024-03-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_patient_patname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='city',
            new_name='patName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
    ]
