# Generated by Django 4.0.2 on 2024-03-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_patient_city_patient_fname_patient_lname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
    ]
