# Generated by Django 4.0.2 on 2024-03-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_patient_patname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
