# Generated by Django 4.0.2 on 2024-03-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_patient_patname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
    ]
